set -g mouse on

set -g history-limit 10000

bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

set -g pane-border-style fg=white

set -g pane-active-border-style fg=green
set -g status-style bg=colour236,fg=colour147

setw -g mode-keys vi
set -g mode-keys vi

set-option -g detach-on-destroy on



bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
