#
# backend = "glx";
# vsync = true;
#
# inactive-opacity = 1.0;
# active-opacity = 1.0;
#
# opacity-rule = [
#     "100:name = 'Calculadora Terminal'",
#     "92:class_g = 'Tilix'",
#     "100:class_g = 'Alacritty'",
#     "85:class_g = 'Rofi'"
# # "95:class_g = 'Code'"
#
# ];
#
# blur:
# {
#     method = "dual_kawase";
#     strength = 9;
#
#     background = true;
#     background-frame = true;
#     background-fixed = false;
#
#     blur-background-exclude = [
#         "window_type = 'dock'",
#         "window_type = 'desktop'",
#         "class_g = 'Conky'"
#     ];
# };
#
# use-damage = true;
# glx-no-stencil = true;
# glx-no-rebind-pixmap = true;
# detect-transient = true;
# detect-client-leader = true;
#
# unredir-if-possible = false;
#
#
#
#
# blur-background-exclude = [
#     "name = 'Calculadora Terminal'",
#     "window_type = 'dock'",
#     "window_type = 'desktop'"
# ];
#
#
#
# para vm
backend = "xrender";
vsync = false;

opacity-rule = [
    "90:class_g = 'Tilix'",

    "100:name = 'Calculadora Terminal'",
    "92:class_g = 'Rofi'",
    "90:class_g = 'Alacritty'"
];

